--- #YAML:1.0
name:               JavaScript-Prepare
version:            v0.1
abstract:           ~
author:
    - Mark Norman Francis <norm@cackhanded.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JavaScript::Minifier::XS:  0
    Modern::Perl:         0
    version:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
